routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'admin'], function () {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
    Route::resource('admin/medias', 'AdminMediasController');
});

Route::get('/admin', function() {
    return view('admin.index');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'photo_id', 'is_active', 'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function role() {
        return $this->belongsTo('App\Role');
    }
    
    public function photo() {
        return $this->belongsTo('App\Photo');
    }
    
    public function setPasswordAttribute($password) {
        if (!empty($password)) {
            $this->attributes['password'] = bcrypt($password);
        }
    }
    
    public function isAdmin() {
        if ($this->role) {
            if ($this->role->name == 'administrator') {
                return true;
            }
        }
        return false;
    }
    
    public function posts() {
        return $this->hasMany('App\Post');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Create user</h1>
    
    @include('includes.form_error')
    
    {{ Form::open(['action' => 'AdminUsersController@store', 'files' => true]) }}
    <div class="form-group">
        {{ Form::label('name', 'Name: ') }}
        {{ Form::text('name', null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('email', 'Email: ') }}
        {{ Form::email('email', null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('role_id', 'Role: ') }}
        {{ Form::select('role_id', [ '' => 'Choose options'] + $roles, null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('is_active', 'Status: ') }}
        {{ Form::select('is_active', ['1' => 'Active', '0' => 'Not Active'], 0, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('photo_id', 'Title: ') }}
        {{ Form::file('photo_id', null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('password', 'Password: ') }}
        {{ Form::password('password', ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::submit('Create User', ['class' => 'btn btn-primary']) }}
    </div>
    {{ Form::close() }}
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Edit user</h1>
    
    <div class="row">
        @include('includes.form_error')
    </div>
    <div class="row">
        <div class="col-sm-3">
            <img src="{{ $user->photo ? url($user->photo->file) : '//placehold.it/400x400' }}" class="img-responsive img-rounded">
        </div>
        <div class="col-sm-9">
            
            {{ Form::model($user, ['method' => 'PATCH', 'route' => ['users.update', $user], 'files' => true]) }}
            <div class="form-group">
                {{ Form::label('name', 'Name: ') }}
                {{ Form::text('name', null, ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                {{ Form::label('email', 'Email: ') }}
                {{ Form::email('email', null, ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                {{ Form::label('role_id', 'Role: ') }}
                {{ Form::select('role_id', [ '' => 'Choose options'] + $roles, null, ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                {{ Form::label('is_active', 'Status: ') }}
                {{ Form::select('is_active', ['1' => 'Active', '0' => 'Not Active'], null, ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                {{ Form::label('photo_id', 'Title: ') }}
                {{ Form::file('photo_id', null, ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                {{ Form::label('password', 'Password: ') }}
                {{ Form::password('password', ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                {{ Form::submit('Edit User', ['class' => 'btn btn-primary col-sm-6']) }}
            </div>
            {{ Form::close() }}
            
            {{ Form::open(['method' => 'DELETE', 'action' => ['AdminUsersController@destroy', $user->id]]) }}
            <div class="form-group">
                {{ Form::submit('Delete user', ['class' => 'btn btn-danger col-sm-6']) }}
            </div>
            {{ Form::close() }}
        </div>
    </div>
@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')

    @if (Session::has('deleted_user'))
    <p class="bg-danger">{{ Session('deleted_user') }}</p>
    @endif

    <h1>Users</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Photo</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Active</th>
                <th>Created</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody>
            @if ($users)
                @foreach ($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td><img height="50" src="{{ $user->photo ? url($user->photo->file) : '//placehold.it/400x400' }}"></td>                    
                    <td><a href="{{ route('users.edit', $user->id) }}">{{ $user->name }}</a></td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->role ? $user->role->name : 'User has no role' }}</td>
                    <td>{{ $user->is_active == 1 ? 'Active' : 'Not active'}}</td>
                    <td>{{ $user->created_at->diffForHumans() }}</td>
                    <td>{{ $user->updated_at->diffForHumans() }}</td>
                </tr>
                @endforeach
            @endif
        </tbody>
  </table>
@stop