routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'admin'], function () {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
    Route::resource('admin/medias', 'AdminMediasController');
});

Route::get('/admin', function() {
    return view('admin.index');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    
    protected $fillable = [
        'category_id',
        'photo_id',
        'title',
        'body'
    ];
    
    public function user() {
        return $this->belongsTo('App\User');
    }
    
    public function photo() {
        return $this->belongsTo('App\Photo');
    }
    
    public function category() {
        return $this->belongsTo('App\Category');
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')


@section('content')
    <h1>Create Post</h1>
    <div class="row">
        @include('includes.form_error')
    </div>
    <div class="row">
        {{ Form::open(['action' => 'AdminPostsController@store', 'files' => true]) }}
        <div class="form-group">
            {{ Form::label('title', 'Title: ') }}
            {{ Form::text('title', null, ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
            {{ Form::label('category_id', 'Category: ') }}
            {{ Form::select('category_id', ['0' => 'Choose category'] + $categories, null, ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
            {{ Form::label('photo_id', 'Photo: ') }}
            {{ Form::file('photo_id', ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
            {{ Form::label('body', 'Description: ') }}
            {{ Form::textarea('body', null, ['class' => 'form-control', 'rows' => 3]) }}
        </div>
        <div class="form-group">
            {{ Form::submit('Create Post', ['class' => 'btn btn-primary']) }}
        </div>
        {{ Form::close() }}
    </div>
@stop

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')


@section('content')
    <h1>Create Post</h1>
    <div class="row">
        @include('includes.form_error')
    </div>
    <div class="row">
        {{ Form::model($post, ['method' => 'PATCH', 'action' => ['AdminPostsController@update', $post->id], 'files' => true]) }}
        <div class="form-group">
            {{ Form::label('title', 'Title: ') }}
            {{ Form::text('title', null, ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
            {{ Form::label('category_id', 'Category: ') }}
            {{ Form::select('category_id', ['0' => 'Choose category'] + $categories, null, ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
            {{ Form::label('photo_id', 'Photo: ') }}
            {{ Form::file('photo_id', ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
            {{ Form::label('body', 'Description: ') }}
            {{ Form::textarea('body', null, ['class' => 'form-control', 'rows' => 3]) }}
        </div>
        <div class="form-group">
            {{ Form::submit('Update Post', ['class' => 'btn btn-primary col-sm-6']) }}
        </div>
        {{ Form::close() }}
        
        {{ Form::open(['method' => 'DELETE', 'action' => ['AdminPostsController@destroy', $post->id]]) }}
            {{ Form::submit('Delete Post', ['class' => 'btn btn-danger col-sm-6']) }}
        {{ Form::close() }}
    </div>
@stop

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')


@section('content')
    <h1>Posts</h1>
    <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Photo</th>
                    <th>Owner</th>
                    <th>Category</th>
                    <th>Title</th>
                    <th>Body</th>
                    <th>Created</th>
                    <th>Updated</th>
                </tr>
            </thead>
            <tbody>
                @if ($posts)
                    @foreach ($posts as $post)
                    <tr>
                        <td>{{ $post->id }}</td>
                        <td><img height="50" src="{{ $post->photo ? url($post->photo->file) : '//placehold.it/400x400' }}"></td>
                        <td><a href="{{ route('posts.edit', $post->id) }}">{{ $post->user->name }}</a></td>
                        <td>{{ $post->category ? $post->category->name : 'Uncategorized' }}</td>
                        <td>{{ $post->title }}</td>
                        <td>{{ str_limit($post->body, 30) }}</td>
                        <td>{{ $post->created_at->diffForHumans() }}</td>
                        <td>{{ $post->updated_at->diffForHumans() }}</td>
                    </tr>
                    @endforeach
                @endif
            </tbody>
    </table>
@stop