routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'admin'], function () {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
    Route::resource('admin/medias', 'AdminMediasController');
});

Route::get('/admin', function() {
    return view('admin.index');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable = [
        'name',
    ];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
<h1>Edit Category</h1>
<div class="col-sm-6">
    {{ Form::model($category, ['method' => 'PATCH', 'action' => ['AdminCategoriesController@update', $category->id]]) }}
    <div class="form-group">
        {{ Form::label('name', 'Name: ') }}
        {{ Form::text('name', null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::submit('Update Category', ['class' => 'btn btn-primary col-sm-6']) }}
    </div>
    {{ Form::close() }}

    {{ Form::open(['method' => 'DELETE', 'action' => ['AdminCategoriesController@destroy', $category->id]]) }}
    <div class="form-group">
        {{ Form::submit('Delete Category', ['class' => 'btn btn-danger col-sm-6']) }}
    </div>
    {{ Form::close() }}
</div>
@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')
<h1>Categories</h1>

<div class="col-sm-6">
    {{ Form::open(['method' => 'POST', 'action' => 'AdminCategoriesController@store']) }}
    <div class="form-group">
        {{ Form::label('name', 'Name: ') }}
        {{ Form::text('name', null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::submit('Create Category', ['class' => 'btn btn-primary']) }}
    </div>
    {{ Form::close() }}
</div>

<div class="col-sm-6">
    
    @if ($categories)
    
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Created date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($categories as $category)
            <tr>
                <td>{{ $category->id }}</td>
                <td><a href="{{ route('categories.edit', $category->id) }}">{{ $category->name }}</a></td>
                <td>{{ $category->created_at ? $category->created_at->diffForHumans() : 'No date' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    @endif
</div>

@stop